<<<<<<< HEAD
# Generated by Django 5.2.6 on 2025-09-07 15:50
=======
# Generated by Django 4.2.24 on 2025-09-08 00:21
>>>>>>> 38c02d0 (feat(tools): implement CRUD API endpoint for tools with tests)

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

<<<<<<< HEAD
    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('agent_id', models.AutoField(primary_key=True, serialize=False)),
                ('agent_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
=======
    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "tool_id",
                    models.AutoField(
                        help_text="Unique ID for each tool.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tool_name",
                    models.CharField(help_text="The name of the tool.", max_length=255),
                ),
                (
                    "tool_description",
                    models.TextField(help_text="A description of what the tool does."),
                ),
                (
                    "meta_data",
                    models.JSONField(
                        help_text="A JSON object that defines the required parameters for the tool."
                    ),
                ),
>>>>>>> 38c02d0 (feat(tools): implement CRUD API endpoint for tools with tests)
            ],
        ),
    ]
